### ISSUE TITLE
in pix2pix.py at line 85 TypeError: __init__() got multiple values for keyword argument 'dtype'

### ISSUE THREAD

**Issue by Microos** [affinelayer/pix2pix-tensorflow#1]
> Tensorflow version: 0.12.1
> Comand: `python pix2pix.py \
  --mode train \
  --output_dir facades_train \
  --max_epochs 200 \
  --input_dir facades/train \
  --which_direction BtoA
`

> Traceback:

`Traceback (most recent call last):
  File "pix2pix.py", line 697, in <module>
    main()
  File "pix2pix.py", line 531, in main
    model = create_model(examples.inputs, examples.targets)
  File "pix2pix.py", line 397, in create_model
    outputs = create_generator(inputs, out_channels)
  File "pix2pix.py", line 318, in create_generator
    output = batchnorm(convolved)
  File "pix2pix.py", line 85, in batchnorm

   ******offset = tf.get_variable("offset",[channels], dtype=tf.float32, initializer=tf.zeros_initializer)******

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 673, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)

******TypeError: __init__() got multiple values for keyword argument 'dtype'******
`

**Comment by christopherhesse** [comment]
What's the output of this: 

python -c "import tensorflow; print(tensorflow.__version__)"

**Comment by Microos** [comment]
It prints “0.12head”. It's slightly different from the expection but `pip freeze` gives “0.12.1”. Thanks.

**Comment by christopherhesse** [comment]
This looks like a change to tensorflow that was made after 0.12.1:

https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0-rc0

tf.zeros_initializer() and tf.ones_initializer() now return a callable that must be called with initializer arguments, in your code replace tf.zeros_initializer with tf.zeros_initializer().

Can you uninstall tensorflow and make sure you have 0.12.1 installed?

**Comment by Microos** [comment]
Sure. And pip freeze doesn't print the version correctly, right? Since I thought 0.12head is same as 0.12.1

**Comment by christopherhesse** [comment]
I don't really know what 0.12head is, it doesn't appear on the tensorflow download page and appears to have a different zeros_initializer :/

**Comment by christopherhesse** [comment]
Closing since it looks like an incorrect version of tensorflow
