### ISSUE TITLE
run pip2pip.py

### ISSUE THREAD

**Issue by dingchengshan** [affinelayer/pix2pix-tensorflow#164]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory 

env
Tensorflow-gpu==1.4.1
CUDA Version: 10.0

Please help me!

**Comment by xuxiangsun** [comment]
I also meet the same question with you.I think you can adjust the version of your tensorflow. The original version of tensorflow of this code is 1.4.1, but it needs CUDA8.0,CUDNN6.0,GCC4.8. But my CUDNN is 7.0+ , so I update the version of tensorflow to 1.5.0 and it realy works. Hope can give you a reference.
