### ISSUE TITLE
dockrun.py error on windows

### ISSUE THREAD

**Issue by Rogerjak1** [affinelayer/pix2pix-tensorflow#165]
I'm trying to run --mode test in Windows 10 64bits using the dockrun.py file after previously being able to run it in Ubuntu 18.04. This is the command I used with success in Ubuntu : 

`python3 tools/dockrun.py python pix2pix.py --mode test --output_dir guerin_test --input_dir ~/pix2pix-tensorflow/deepterrains-dataset/multi/test --checkpoint ~/pix2pix-tensorflow/multi-train`

Went over to Windows 10 where I set up my folder in the same way as in Ubuntu and tried to run --mode test with this command:

 `python3 .\tools\dockrun.py python2 pix2pix.py --mode test --output_dir guerin_test --input_dir .\deepterrains-dataset\multi\test --checkpoint multi_train`

Unfortunately I get this error:

> running sudo 'C:\Program Files\Docker\Docker\Resources\bin\docker.EXE' run --rm --volume /:/host --workdir '/hostC:\Users\Rogerjak\pix2pix-tensorflow' --env PYTHONUNBUFFERED=x --env CUDA_CACHE_PATH=/host/tmp/cuda-cache affinelayer/pix2pix-tensorflow:v3 python2 pix2pix.py --mode test --output_dir guerin_test --input_dir '.\deepterrains-dataset\multi\test' --checkpoint multi_train
Traceback (most recent call last):
  File ".\tools\dockrun.py", line 112, in <module>
    main()
  File ".\tools\dockrun.py", line 109, in main
    os.execvp(args[0], args)
  File "C:\Python3\lib\os.py", line 571, in execvp
    _execvpe(file, args)
  File "C:\Python3\lib\os.py", line 613, in _execvpe
    raise last_exc
  File "C:\Python3\lib\os.py", line 604, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory 

I tried messing around with dockrun.py in hopes I would fix my problem (the pathing to the workdir starting with  '/hostC:\ is suspicious) but I can't figure out why exactly I'm getting a _FileNotFoundError_... I have docker installed, Python and I am running the command from the correct folder.

Any help or pointers to solve this problem would be most appreciated!

Thanks in advance,
Rodrigo

**Comment by LeoYuanjieLi** [comment]
I couldn't get get it running either.

However the non-docker version is working
