### ISSUE TITLE
export checkpoint error

### ISSUE THREAD

**Issue by OhRly-net** [affinelayer/pix2pix-tensorflow#171]
I've succesfully made new models before, but in my last attempt at making a new model, i stumbled upon this error while creating the model from the checkpoint:

```
Writing variable generator/decoder_2/batch_normalization/moving_variance...
Writing variable generator/decoder_8/batch_normalization/moving_mean...
Writing variable generator/decoder_1/conv2d_transpose/bias...
Writing variable generator/decoder_1/conv2d_transpose/kernel...
Writing variable generator/decoder_7/batch_normalization/gamma...
Writing variable generator/decoder_2/batch_normalization/beta...
Writing variable generator/decoder_7/batch_normalization/moving_mean...
Writing variable generator/decoder_2/conv2d_transpose/bias...
Writing variable generator/decoder_6/conv2d_transpose/kernel...
Writing variable generator/decoder_2/batch_normalization/gamma...
Writing variable generator/decoder_2/batch_normalization/moving_mean...
Writing variable generator/decoder_3/batch_normalization/moving_mean...
Writing variable generator/encoder_2/batch_normalization/gamma...
Writing variable generator/decoder_2/conv2d_transpose/kernel...
Writing variable generator/decoder_3/batch_normalization/beta...
Writing variable generator/encoder_3/conv2d/kernel...
Writing variable generator/decoder_3/batch_normalization/gamma...
Writing variable generator/decoder_3/batch_normalization/moving_variance...
Writing variable generator/decoder_8/batch_normalization/moving_variance...
Writing variable generator/decoder_3/conv2d_transpose/bias...
Writing variable generator/decoder_3/conv2d_transpose/kernel...
Writing variable generator/decoder_4/batch_normalization/beta...
Writing variable generator/decoder_4/batch_normalization/gamma...
Writing variable generator/decoder_8/conv2d_transpose/kernel...
Writing variable generator/encoder_4/conv2d/kernel...
Writing variable generator/encoder_2/batch_normalization/moving_variance...
Writing variable generator/decoder_4/batch_normalization/moving_mean...
Writing variable generator/decoder_7/conv2d_transpose/bias...
Writing variable generator/decoder_4/batch_normalization/moving_variance...
Writing variable generator/decoder_4/conv2d_transpose/bias...
Writing variable generator/decoder_4/conv2d_transpose/kernel...
Writing variable generator/encoder_6/batch_normalization/gamma...
Writing variable generator/decoder_5/batch_normalization/beta...
Writing variable generator/decoder_5/batch_normalization/gamma...
Writing variable generator/encoder_7/batch_normalization/moving_variance...
Writing variable generator/decoder_5/batch_normalization/moving_mean...
Writing variable generator/encoder_2/conv2d/bias...
Writing variable generator/decoder_5/batch_normalization/moving_variance...
Writing variable generator/encoder_4/batch_normalization/beta...
Writing variable generator/decoder_5/conv2d_transpose/bias...
Writing variable generator/decoder_6/batch_normalization/moving_variance...
Writing variable generator/decoder_5/conv2d_transpose/kernel...
Writing variable generator/decoder_6/batch_normalization/beta...
Writing variable generator/decoder_6/conv2d_transpose/bias...
Writing variable generator/encoder_7/batch_normalization/moving_mean...
Writing variable generator/decoder_6/batch_normalization/gamma...
Writing variable generator/decoder_6/batch_normalization/moving_mean...
Writing variable generator/decoder_7/batch_normalization/beta...
Writing variable generator/decoder_8/batch_normalization/gamma...
Writing variable generator/encoder_4/batch_normalization/gamma...
Writing variable generator/decoder_7/batch_normalization/moving_variance...
Writing variable generator/encoder_2/batch_normalization/beta...
Writing variable generator/decoder_7/conv2d_transpose/kernel...
Writing variable generator/encoder_1/conv2d/kernel...
Writing variable generator/decoder_8/batch_normalization/beta...
Writing variable generator/decoder_8/conv2d_transpose/bias...
Writing variable generator/encoder_4/conv2d/bias...
Writing variable generator/encoder_1/conv2d/bias...
Writing variable generator/encoder_3/conv2d/bias...
Writing variable generator/encoder_2/batch_normalization/moving_mean...
Writing variable generator/encoder_2/conv2d/kernel...
Writing variable generator/encoder_3/batch_normalization/beta...
Writing variable generator/encoder_6/batch_normalization/beta...
Writing variable generator/encoder_3/batch_normalization/gamma...
Writing variable generator/encoder_3/batch_normalization/moving_mean...
Writing variable generator/encoder_3/batch_normalization/moving_variance...
Writing variable generator/encoder_4/batch_normalization/moving_mean...
Writing variable generator/encoder_4/batch_normalization/moving_variance...
Writing variable generator/encoder_5/batch_normalization/beta...
Writing variable generator/encoder_5/batch_normalization/gamma...
Writing variable generator/encoder_5/batch_normalization/moving_mean...
Writing variable generator/encoder_5/batch_normalization/moving_variance...
Writing variable generator/encoder_5/conv2d/kernel...
Writing variable generator/encoder_5/conv2d/bias...
Writing variable generator/encoder_6/batch_normalization/moving_mean...
Writing variable generator/encoder_6/batch_normalization/moving_variance...
Writing variable generator/encoder_6/conv2d/bias...
Writing variable generator/encoder_6/conv2d/kernel...
Writing variable generator/encoder_7/batch_normalization/beta...
Writing variable generator/encoder_7/batch_normalization/gamma...
Writing variable generator/encoder_7/conv2d/bias...
Writing variable generator/encoder_7/conv2d/kernel...
Writing variable generator/encoder_8/batch_normalization/beta...
Writing variable generator/encoder_8/batch_normalization/gamma...
Writing variable generator/encoder_8/batch_normalization/moving_mean...
Writing variable generator/encoder_8/batch_normalization/moving_variance...
Writing variable generator/encoder_8/conv2d/bias...
Writing variable generator/encoder_8/conv2d/kernel...
Writing manifest to C:\Users\user\AppData\Local\Temp\tmpxs7j_1r8\manifest.json
Traceback (most recent call last):
  File "server\tools\export-checkpoint.py", line 101, in <module>
    main()
  File "server\tools\export-checkpoint.py", line 63, in main
    with open(os.path.join(tmp_dir, value["filename"]), "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpxs7j_1r8\\generator_encoder_8_batch_normalization_gamma'
```
Anyone got an idea why I get this error?

**Comment by OhRly-net** [comment]
edit: fixed it by changing 
```
checkpoint_file = os.path.join(args.checkpoint, model_path)
    with tempfile.TemporaryDirectory() as tmp_dir:
        cmd = ["python", "-u", os.path.join(SCRIPT_DIR, "dump_checkpoints/dump_checkpoint_vars.py"), "--model_type", "tensorflow", "--output_dir", tmp_dir, "--checkpoint_file", checkpoint_file]
        sp.check_call(cmd)
```
to
```
checkpoint_file = os.path.join(args.checkpoint, model_path)
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_dir = "D:/AI/pix2pix-tensorflow/server/tools/tmp/" # change this to another temp dir
        cmd = ["python", "-u", os.path.join(SCRIPT_DIR, "dump_checkpoints/dump_checkpoint_vars.py"), "--model_type", "tensorflow", "--output_dir", tmp_dir, "--checkpoint_file", checkpoint_file]
        sp.check_call(cmd)
```
and adding this folder to the Windows Defender Exceptions

Windows Defender sees the generated "generator_encoder_8_batch_normalization_gamma" file as a virus for some reason...

Virustotal link: https://www.virustotal.com/gui/file/40dbbc12ef8f3e2fd7a8a8ae6f390593b8d6f93304d7e65b82553af652b30b10/detection
