### ISSUE TITLE
picture merging

### ISSUE THREAD

**Issue by Lucretious** [affinelayer/pix2pix-tensorflow#179]
Hi,

I am quite new to python and tensorflow, but I liked the possibilities of your script, so I tried it. But I cannot find tensorflow 1.4. The earliest version to install seems to be 1.13. And there seem to have been a few changes to the internal code in tf, since 1.4.  When I try to run your merge-code:

$ python tools/process.py \
>   --input_dir a \
>   --b_dir b \
>   --operation combine \
>   --output_dir c

i get some errors telling me, that there are functions used, that don´t exist in tf 1.13 anymore. I also tried the newer versions up to tf 2.0. Is there a way to install the old versions of tf? Doing this with pip doesn´t work. Or can someone tell me, how to change code, if it isn´t to complex for a newbie?

Here´s the full error-message I get:

WARNING:tensorflow:From E:\Python\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:3528: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().
WARNING:tensorflow:From E:\Python\Python37\lib\site-packages\tensorflow\python\ops\control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "tools/process.py", line 306, in <module>
    main()
  File "tools/process.py", line 242, in main
    for src_path in im.find(a.input_dir):
  File "C:\Users\Master\pix2pix-tensorflow\tools\tfimage.py", line 115, in find
    for filename in os.listdir(d):

**Comment by ReidTissing** [comment]
I hope you've solved this by now, but if it helps anyone in the future: 
Python 3.7 doesn't support Tensorflow GPU, but Python **3.6** does. Creating a virtual environment in conda or the GPU-supported Windows Linux Subsystem should get you up and running. Here's a [link](https://stackoverflow.com/questions/59650012/install-an-older-version-of-tensorflow-gpu) with the resolved issue.
