### ISSUE TITLE
module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'

### ISSUE THREAD

**Issue by VijayaMalla** [affinelayer/pix2pix-tensorflow#192]
I am trying to run pix2pix.py and I got an error at line 540, 
OLD : #tf.set_random_seed(a.seed)
NEW :  tf.random.set_seed(a.seed)

after that when I run the command again, I am getting this error
Traceback (most recent call last):
  File "pix2pix.py", line 805, in <module>
    main()
  File "pix2pix.py", line 627, in main
    examples = load_examples()
  File "pix2pix.py", line 259, in load_examples
    path_queue = tf.train.string_input_producer(input_paths, shuffle=a.mode == "train")
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'string_input_producer'

I didn't make any changes, just following the steps at this [pix2pix](https://affinelayer.com/pix2pix/). Please HELP.

**Comment by Zoe861122** [comment]
maybe you can add this:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

and at line 540 still use OLD : #tf.set_random_seed(a.seed)
