### ISSUE TITLE
How to use the export model?

### ISSUE THREAD

**Issue by youansheng** [affinelayer/pix2pix-tensorflow#35]
rt. how to use the exported model.

**Comment by nonoesp** [comment]
Hi @youansheng. Once you export your model, you can use https://github.com/affinelayer/pix2pix-tensorflow/blob/master/server/tools/process-local.py to process individual images.

If you see the declaration of arguments in `process-local.py`, you can see the following settings that need to be given:

```
--model_dir // directory containing exported model
--input_file // input PNG image file
--output_file // output PNG image file
```

If you've used `pix2pix.py` as it is provided in this repository, you will have to provide an `input_file` of 256x256 encoded as a PNG image.

Here is a sample call to generate an image.

```
python /path/to/pix2pix.py --model_dir /path/to/exported_model --input_file /path/to/input_file.png --output_file /path/to/output_file.png
```

**Comment by youansheng** [comment]
Thanks!!!

**Comment by anandanand84** [comment]
@nonoesp @youansheng I am trying to use the process-local.py command with my custom data which I used for training(i.e before combining) and I get the following error

```
raceback (most recent call last):
  File "server/tools/process-local.py", line 45, in <module>
    main()
  File "server/tools/process-local.py", line 34, in main
    output_value = sess.run(output, feed_dict={input: np.expand_dims(input_value, axis=0)})[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,2,2,512] vs. shape[1] = [1,3,3,512]
	 [[Node: generator/decoder_7/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/decoder_8/dropout/mul, generator/encoder_7/batchnorm/batchnorm/add_1, generator/decoder_7/concat/axis)]]

Caused by op u'generator/decoder_7/concat', defined at:
  File "server/tools/process-local.py", line 45, in <module>
    main()
  File "server/tools/process-local.py", line 26, in main
    saver = tf.train.import_meta_graph(a.model_dir + "/export.meta")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1566, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 498, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 288, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,2,2,512] vs. shape[1] = [1,3,3,512]
	 [[Node: generator/decoder_7/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/decoder_8/dropout/mul, generator/encoder_7/batchnorm/batchnorm/add_1, generator/decoder_7/concat/axis)]]

```

**Comment by anandanand84** [comment]
my bad I was using wrong size image

**Comment by humayun** [comment]
Hi,

I found error when run the exported model for test image. 
Here is command I used to generate export model: 
 python pix2pix.py --mode export --output_dir /home/humayun/export/  --checkpoint /home/humayun/trained_model/ --which_direction AtoB

It generate five files: checkpoint, export.data-00000-of-00001, export.index, export.meta and options.json. 

When I run this command for test image, I gave me error:
python server/tools/process-local.py --model_dir /home/humayun/export  --input_file /home/humayun/b2_029775990.png --output_file test.png

The error message is: 
2017-08-17 13:44:11.041785: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 2, computed = 1
Traceback (most recent call last):
  File "server/tools/process-local.py", line 45, in <module>
    main()
  File "server/tools/process-local.py", line 34, in main
    output_value = sess.run(output, feed_dict={input: np.expand_dims(input_value, axis=0)})[0]
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 2, computed = 1
         [[Node: generator/decoder_8/deconv/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/decoder_8/deconv/conv2d_transpose/output_shape, generator/decoder_8/deconv/filter/read, generator/decoder_8/Relu)]]

Caused by op u'generator/decoder_8/deconv/conv2d_transpose', defined at:
  File "server/tools/process-local.py", line 45, in <module>
    main()
  File "server/tools/process-local.py", line 26, in main
    saver = tf.train.import_meta_graph(a.model_dir + "/export.meta")
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 311, in import_graph_def
    op_def=op_def)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 2, computed = 1
         [[Node: generator/decoder_8/deconv/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/decoder_8/deconv/conv2d_transpose/output_shape, generator/decoder_8/deconv/filter/read, generator/decoder_8/Relu)]]

**Comment by humayun** [comment]
I fixed the problem. Actually I was giving initially combined image. When I gave only single image, it worked good. 

-Humayun

**Comment by danielkaifeng** [comment]
why there isn't process-local.py files in server/tools now?

**Comment by franciscorba** [comment]
@danielkaifeng 

In Issue #112 They said that the file could be found here: 

[https://github.com/affinelayer/pix2pix-tensorflow/blob/a92fdb3bc3c5e2ea3cb7c53e2cb955851fbcc6d2/server/tools/process-local.py](url)

I download it got some errors. 

They also said that it was removed because now is intended to be done with deeplearnjs, but I don't know how.

**Comment by TaeheeJeong** [comment]
Any answer for process_local.py?
