### ISSUE TITLE
training / testing 

### ISSUE THREAD

**Issue by sinsunsan** [affinelayer/pix2pix-tensorflow#4]
Hello, 

Thanks  for this great work. My first experience with tensor flow. I have installed it without problem. 

Can you tell us, if there is a minimum training time ? 
Does training end or we need to end it manually ? 

Idem for testing is it possible to test quickly after a view minutes training (just to test that it show something  ? )

I interompted the training after a few minutes 

and test typed testing command

at the end I had this error 
````py
loading model from checkpoint
Traceback (most recent call last):
  File "pix2pix.py", line 800, in <module>
    main()
  File "pix2pix.py", line 716, in main
    saver.restore(sess, checkpoint)
  File "/Users/slucas/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/slucas/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Users/slucas/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/slucas/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Users/slucas/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.
````
and the files in this screenshots
![screen shot 2017-02-22 at 22 52 31](https://cloud.githubusercontent.com/assets/910241/23234211/9d805fcc-f951-11e6-86c1-c1ae4bfa9972.png)

What are they temporary files ? 

Files to keep that will be improved by further training / testing ?

**Comment by christopherhesse** [comment]
Check out the `--help` option.  The ones you might like the most are `--save_freq 1` to save every step `--display_freq 1` to display output of the network while training (once again, on each step).
