### ISSUE TITLE
How to export the model and test the export model.

### ISSUE THREAD

**Issue by humayun** [affinelayer/pix2pix-tensorflow#63]
Dear All,

I found errors when run the exported model for test image.
Here is command I used to export model:
python pix2pix.py --mode export --output_dir /home/humayun/export/ --checkpoint /home/humayun/trained_model/ --which_direction AtoB

It generate five files: checkpoint, export.data-00000-of-00001, export.index, export.meta and options.json.

When I run this command for test image, I gave me error:
python server/tools/process-local.py --model_dir /home/humayun/export --input_file /home/humayun/b2_029775990.png --output_file test.png

The error message is:
2017-08-17 13:44:11.041785: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 2, computed = 1
Traceback (most recent call last):
File "server/tools/process-local.py", line 45, in
main()
File "server/tools/process-local.py", line 34, in main
output_value = sess.run(output, feed_dict={input: np.expand_dims(input_value, axis=0)})[0]
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
run_metadata_ptr)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
feed_dict_string, options, run_metadata)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
target_list, options, run_metadata)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 2, computed = 1
[[Node: generator/decoder_8/deconv/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/decoder_8/deconv/conv2d_transpose/output_shape, generator/decoder_8/deconv/filter/read, generator/decoder_8/Relu)]]

Caused by op u'generator/decoder_8/deconv/conv2d_transpose', defined at:
File "server/tools/process-local.py", line 45, in
main()
File "server/tools/process-local.py", line 26, in main
saver = tf.train.import_meta_graph(a.model_dir + "/export.meta")
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
**kwargs)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
producer_op_list=producer_op_list)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 311, in import_graph_def
op_def=op_def)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/home/humayun/MD_Stuff/tensorflow_1.2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in init
self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 2, computed = 1
[[Node: generator/decoder_8/deconv/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/decoder_8/deconv/conv2d_transpose/output_shape, generator/decoder_8/deconv/filter/read, generator/decoder_8/Relu)]]

**Comment by humayun** [comment]
I fixed the problem. Actually I was giving initially combined image. When I gave only single image, it worked good. 

-Humayun

**Comment by danielnjoo** [comment]
@humayun hi! I'm running into the exact same error, and i'm passing it single images... any idea what might be causing the error? i trained the model with paired data

**Comment by humayun** [comment]
Hi Danieljoo,

First Step:  to resize the original images and mask images to 256x256 sized images.
Second step: After resizing, next step is combining them (original and mask images). I used pix2pix code to combine original and mask images: 
	◦	python pix2pix/tools/process.py --input_dir resizied_a  --b_dir resized_b  --operation combine --output_dir resized_combined

**Comment by MuhammadAsadJaved** [comment]
@humayun  Can you explained the procedure you followed please? 
I am unable to generate test image after training.  
I have both visual images and infrared images and i want to generate new infrared images from visual images after training. 
i followed these steps. 
1-combine visual and infrared images from folder a and b into folder c. 
2-trained the model on folder c 
3-export the trained model (Here we have to export the model from trained folder or test folder?)
4-generate test image using given python in the issues.  but it throw some error. 

I want to train from the start again. Can you explain me the procedure? 
waiting for your response. 
Thank you very much.

**Comment by MuhammadAsadJaved** [comment]
@humayun  I can run it after i resized the input image to 256 x 256 , Can't we use the different size input image? or if we train on different size  for example 416 x 416 , can we generate the new images with this size?

**Comment by MuhammadAsadJaved** [comment]
I found the answers.
