### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by krwarner** [affinelayer/pix2pix-tensorflow#80]
When trying to use the combine function of the tools/process.py to combine two directories I get the following error:

`pix2pix-tensorflow>python tools/process.py --input_dir resized_a1 --b_dir resized_b --operation combine --output_dir c
skipping 0 files that already exist
processing 32961 files
2017-11-07 09:12:08.660339: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "tools/process.py", line 306, in <module>
    main()
  File "tools/process.py", line 270, in main
    process(src_path, dst_path)
  File "tools/process.py", line 202, in process
    dst = combine(src, src_path)
  File "tools/process.py", line 107, in combine
    return np.concatenate([src, sibling], axis=1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly`

I thought it may be an issue with the 32 bit depth images that I am using, considering everything else seems to be as it should be (same # of images, same file names, etc.) but it appears that the code should convert it to the necessary 8 bit depth, so it doesn't appear that the bit depth should have any effect on the input dimensions. 

Any ideas on what is going on here?

**Comment by haqkiemdaim** [comment]
@krwarner have you solve this problem? How ya ?

**Comment by krwarner** [comment]
> @krwarner have you solve this problem? How ya ?

@DrHaqkiem I believe I did, it has been awhile though, so let me dig into the code again and see how I made it work.
