### ISSUE TITLE
Error using exported model with process-local

### ISSUE THREAD

**Issue by Hiromi-nee** [affinelayer/pix2pix-tensorflow#90]
`$ python3.5 server/tools/process-local.py --model_dir `pwd`/facades_export --input_file ./server/static/facades-input.png --output_file ./a.png
2017-12-25 11:28:35.135374: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-25 11:28:35.256479: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-25 11:28:35.256761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.58GiB
2017-12-25 11:28:35.256779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "server/tools/process-local.py", line 45, in <module>
    main()
  File "server/tools/process-local.py", line 28, in main
    input_vars = json.loads(tf.get_collection("inputs")[0])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`

model was exported using instructions on README.md

**Comment by ccpocker** [comment]
**I have faced the same problem. I trained a model in server and export it. But when i test the trained model in my local computer,error occured.**
Traceback (most recent call last):
  File "pix2pix.py", line 803, in <module>
    main()
  File "pix2pix.py", line 717, in main
    checkpoint = tf.train.latest_checkpoint(a.checkpoint)
  File "/home/yjl/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1722, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "/home/yjl/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 333, in get_matching_files
    for single_filename in filename
  File "/home/yjl/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/518TechWeek/pix2pix-tensorflow/model_path; No such file or directory
**But it works when i test the trained model in server. How can I fix this Problem?**

**Comment by dustyYMelody7** [comment]
If you know the reason, please tell me.  Very appreciated!
