### ISSUE TITLE
Octave fails in docker

### ISSUE THREAD

**Issue by ablenesi** [affinelayer/pix2pix-tensorflow#95]
I'm getting the following error when running the `python3 tools/dockrun.py python tools/process.py ... --operation edges`

```octave failed
returncode: -6
output: octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
warning: your version of GraphicsMagick limits images to 16 bits per pixel
warning: called from
    imformats>default_formats at line 256 column 11
    imformats at line 79 column 3
    imwrite at line 99 column 7
panic: panic: attempted clean up apparently failed -- aborting...
panic: attempted clean up apparently failed -- aborting...
panic: attempted clean up apparently failed -- aborting...
Segmentation fault -- stopping myself...
attempting to save variables to 'octave-workspace'...

Traceback (most recent call last):
  File "tools/process.py", line 323, in <module>
    main()
  File "tools/process.py", line 287, in main
    process(src_path, dst_path)
  File "tools/process.py", line 221, in process
    dst = edges(src)
  File "tools/process.py", line 200, in edges
    subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['octave', '--eval', 'threshold=0.0980392156863;', '--eval', "output_path='/tmp/tmpYETw82.png';", '--eval', "input_path='/tmp/tmpjbniFA.mat';", '--eval', 'small_edge=10;', '--eval', 'image_width=256;', '--eval', "\nE = 1-load(input_path).input;\nE = imresize(E, [image_width,image_width]);\nE = 1 - E;\nE = single(E);\n[Ox, Oy] = gradient(convTri(E, 4), 1);\n[Oxx, ~] = gradient(Ox, 1);\n[Oxy, Oyy] = gradient(Oy, 1);\nO = mod(atan(Oyy .* sign(-Oxy) ./ (Oxx + 1e-5)), pi);\nE = edgesNmsMex(E, O, 1, 5, 1.01, 1);\nE = double(E >= max(eps, threshold));\nE = bwmorph(E, 'thin', inf);\nE = bwareaopen(E, small_edge);\nE = 1 - E;\nE = uint8(E * 255);\nimwrite(E, output_path);\n"]' returned non-zero exit status -6
```

**Comment by dwillbarron** [comment]
I found the problem causing this issue. The dockerfile installs Octave from the Ubuntu repos, which serves version 4.0.0, which is affected by the following issue: https://savannah.gnu.org/bugs/?41699

To fix this, you just need to get a more recent version of Octave installed in the docker image. Here's the change I made to the Dockerfile to get it working:

Replace
```
RUN apt-get install -y --no-install-recommends octave liboctave-dev && \
```

With
```
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:octave/stable && \
    apt-get update && \
    apt-get install -y octave liboctave-dev \
```
With that, it's working for me now.
If you're using dockrun.py, don't forget to change the code to point to the new docker image you've built.

**Comment by Rogerjak1** [comment]
> I found the problem causing this issue. The dockerfile installs Octave from the Ubuntu repos, which serves version 4.0.0, which is affected by the following issue: https://savannah.gnu.org/bugs/?41699
> 
> To fix this, you just need to get a more recent version of Octave installed in the docker image. Here's the change I made to the Dockerfile to get it working:
> 
> Replace
> 
> ```
> RUN apt-get install -y --no-install-recommends octave liboctave-dev && \
> ```
> 
> With
> 
> ```
> RUN apt-get install -y software-properties-common && \
>     add-apt-repository -y ppa:octave/stable && \
>     apt-get update && \
>     apt-get install -y octave liboctave-dev \
> ```
> 
> With that, it's working for me now.
> If you're using dockrun.py, don't forget to change the code to point to the new docker image you've built.

I tried this solution and after a lot of tries,  google searches and changes it kept returning me: _The command '/bin/sh -c apt-get install -y software-properties-common && add-apt-repository -y ppa:octave/stable && apt-get update -y && apt-get install -y octave liboctave-dev     octave --eval "pkg install -forge image" && echo "pkg load image;" >> /root/.octaverc' returned a non-zero code: 100_

As a final desperate measure I rewrote the block as such to try to understand where exactly was I getting the error: 
```
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:octave/stable
RUN apt-get update -y 
RUN apt-get install -y octave liboctave-dev 
RUN octave --eval "pkg install -forge image" 
RUN echo "pkg load image;" >> /root/.octaverc
```
and it worked...I also added the _--no-cache_ option when doing docker build.
